### ISSUE TITLE
fis2中的simple有这个  data-fixed

### ISSUE THREAD

**Issue by 303182519** [fex-team/fis3-postpackager-loader#14]
fis3能加上吗

**Comment by 303182519** [comment]
因为有的是想固定在头部的js，没办法

**Comment by 2betop** [comment]
`<!--ignore-->` 表示忽略此资源，插在`</script>` 后面，应该能满足你的需求。

**Comment by luozt** [comment]
@2betop 加了ignore还是不行，已做[示例项目](https://github.com/luozt/public-static/tree/b8ee23cb9b13afd0e9b173ec39d445fe5acca615)，可参考看看。fis3-postpackager-loader插件会影响data-fixed功能使用

**Comment by 2betop** [comment]
你升级下试试，会不会是版本问题。

**Comment by luozt** [comment]
我分别在node v4.4.1, node v6.2.2的环境试过了，的确loader Plugin是会影响data-fixed的正常使用。可看看我上面提到的示例项目↑

**Comment by 2betop** [comment]
`<!--ignore-->` 和 `</script>` 之前不能有任何字符。不要断行

在fis3 里面没有data-fixed 直接去掉吧。

**Comment by luozt** [comment]
的确是你说的那样，谢谢！（当时测试时，没留意ignore紧跟着script标签...）
