### ISSUE TITLE
loader 可以使用变量进行异步加载吗？

### ISSUE THREAD

**Issue by BelinChung** [fex-team/fis3-postpackager-loader#15]
在 autoload 中，可以用声明资源或使用 include 属性新增额外的资源到 resourceMap 中
因为额外的资源比较多，loader 是否有类似于 autoload 中 include 属性的东西，或者有其他更好的方法实现使用变量进行异步加载？

**Comment by BelinChung** [comment]
补充一下：
使用场景是 CodeMirror 
在选择不同的代码类型的时候需要异步加载不同的代码高亮规则 JS ，类型非常多
https://github.com/codemirror/CodeMirror/tree/master/mode

``` javascript
//监听select的变化
$("#snippetType").on('change', function () {
    that.snippetType = $(this).val();
    var modeURL = modeURLBase.replace(/%N/g, that.snippetType);
    require.async(modeURL, function() {
         that.codeEditor.setOption("mode", that.snippetType);
    })
});
```
如果在头部声明依赖的话，似乎不太实际，有没有类似 autoload 的这个功能
https://github.com/hefangshi/fis-pure-dynamic-async-demo/blob/master/fis-conf.js#L1

**Comment by 2betop** [comment]
你的意思是，可以通过 glob 或者正则，命中一堆 module 然后，让他们都在 resoucemap 表里面，方便运行时异步加载？

**Comment by BelinChung** [comment]
@2betop 应该是这样的！

**Comment by 2betop** [comment]
了解了，马上开始实现。

**Comment by 2betop** [comment]
fis3-postpackager-loader@1.2.8 

已支持此功能，注意文档中的说明。
