### ISSUE TITLE
html 文件中 require('xxx') 不能正常生成 resoureceMap

### ISSUE THREAD

**Issue by hanai** [fex-team/fis3-postpackager-loader#19]
采用 hook-commonjs + postpackager-loader + mod.js 方案。

html 文件中写 `require(['jquery'])` 的方式可以正常生成resourceMap，用 `require('jquery')` 就没有resourceMap 生成。

**Comment by 2betop** [comment]
同步的不需要生成，直接页面里面通过 `<script>` 加载了

**Comment by hanai** [comment]
呃，确实有js加载但是
```
Uncaught [ModJS] Cannot find module 'xxx'
```

看生成的html里是这样的
``` html
<script>
require('xxx');
</script>
<script src="modules/xxx"></script>
```
script跑到require的下面了，导致执行require('xxx')的时候module还没有载入。

配置如下
``` js
fis.hook('commonjs', {
    paths: {
        jquery: '/deps/jquery/jquery'
    },
    baseUrl: '/modules'
});

fis.match('::package', {
    postpackager: fis.plugin('loader', {
        resourceType: 'mod',
        useInlineMap: false,
        obtainScript: false,
        obtainStyle: false
    })
});
```

**Comment by 2betop** [comment]
你吧 `obtainScript` 给关了，你通过  `<script>` 引入的 js 的依赖没有被加载。

**Comment by hanai** [comment]
哦，确实是这样的。
能不能解释一下
```
obtainScript 是否收集 <script> 内容。（非页面依赖部分）
obtainStyle 是否收集 <style> 和 <link> 内容。（非页面依赖部分）
```
具体是做了什么，我观察到了选true了后通过link和script引入的内容的在html文件中的位置会改变。

**Comment by 2betop** [comment]
通过 `<script> ` 引入的 js， 改 js 内部可能用了其他依赖。如果你不设置 `obtainScript` 该 js 中的依赖是不会加载的。

loader 会收集所有的 js 依赖，统一在页脚输出。如果你想控制位置，请通过 placeholder 注释控制，具体请看 loader 中的文档说明。

**Comment by hanai** [comment]
了解了
