### ISSUE TITLE
allInOne的时候，如何把线上的css一起打包？

### ISSUE THREAD

**Issue by lys623** [fex-team/fis3-postpackager-loader#24]
如题；    
    link rel="stylesheet" type="text/css" href="http://misc.buy.com/lib/skin/2013/base.css" />
    link rel="stylesheet" type="text/css" href="/widget/footer/footer.css" />
    link rel="stylesheet" type="text/css" href="/widget/header/header.css" />
只打包了footer，header，怎么配置把base.css也一起打包

**Comment by xiangshouding** [comment]
远端 css 不处理
