### ISSUE TITLE
不支持 es6 后缀的文件

### ISSUE THREAD

**Issue by hanai** [fex-team/fis3-postpackager-loader#3]
resource.js
``` js
id.replace(/\.js$/i, '');
uri.replace(/\.js$/i, '');
```

**Comment by 2betop** [comment]
你没有设置 rExt 为 js 吗？

**Comment by hanai** [comment]
有设置的。
呃，这个和hook-module也有关，
https://github.com/fex-team/fis3-hook-module/blob/master/lib/amd.js
下也有
``` js
function findResource(name, path) {
  var extList = ['.js', '.coffee', '.jsx'];
  var info = fis.uri(name, path);

  for (var i = 0, len = extList.length; i < len && !info.file; i++) {
    info = fis.uri(name + extList[i], path);
  }

  return info;
}
```
导致 .es6 不会被识别为resource，
然后
https://github.com/fex-team/fis3-postpackager-loader/blob/master/lib/resource.js
中有
``` js
/\.js$/i.test(id) && reqs.push('\'' + id.replace(/\.js$/i, '') + '\'');
```
也和后缀有关。

**Comment by 2betop** [comment]
骚等，我搞个 demo ，跑下你提供 babel 插件就知道了。

**Comment by hanai** [comment]
@2betop 需要我提供babel-parser？

**Comment by 2betop** [comment]
这块，确实是问题比较多。之前一些写法都比较死。不过现在基本上解决了。

这是 demo https://github.com/fex-team/fis3-demo/tree/master/use-es6

请更新 fis3, fis3-hook-module, fis3-postpackager-loader

**Comment by 2betop** [comment]
@hanai 快看看，更新后，问题解决了没有。

**Comment by hanai** [comment]
ok
