### ISSUE TITLE
[fis3-postpackager-loader]"<!--RESOURCEMAP_PLACEHOLDER-->"导致生成无用代码

### ISSUE THREAD

**Issue by worry127722** [fex-team/fis3-postpackager-loader#5]
当useInlineMap设置为true，
之后 在html页面中加入 ，
在html代码中会生成无用代码 如下图
<img width="637" alt="78305f89cee1baf4e5e9e2b41bd3e2fc" src="https://cloud.githubusercontent.com/assets/6937117/9053440/82a85052-3aa7-11e5-9384-041acceb6810.png">

**Comment by 2betop** [comment]
不能重现，麻烦 git pull 后重试

**Comment by worry127722** [comment]
此问题首先需要在html页面中 添加代码  
如下所示：
<body>
  <p>1236</p>
  
</body>

然后设置  useInlineMap: true   ，
之后即可复现

**Comment by worry127722** [comment]
已修复
