### ISSUE TITLE
使用 useSameNameRequire css依赖关系不准确

### ISSUE THREAD

**Issue by maxming2333** [fex-team/fis3-postpackager-loader#61]
如图：

![Alt text](http://ww2.sinaimg.cn/large/72f96cbagw1f5d76kzhv4j206504vglk)

`html` 同名依赖 `qmqz`目录下的 css 和 js

其中 `qmqz.js` require 了 `tpl4.js`

因为在同名依赖滴作用下 `tpl4.js` 依赖了 `tpl4.css`

依赖链 ： 

```
qmqz.html -> qmqz.js -> tpl4.js -> tpl4.scss
qmqz.html -> qmqz.js -> qmqz.scss
```

按道理

load 合并滴时候

`tpl4.scss` 应该是在 `qmqz.scss` 之前滴，但是打包出来滴效果却是

`qmqz.scss` 第一
`tpl4.scss` 第二

这样就导致 `qmqz.scss` 不能覆盖 `tpl4.scss` 里面的样式

**Comment by 2betop** [comment]
求来个仓库，方便修复问题。

**Comment by maxming2333** [comment]
`git地址` : [https://github.com/maxming2333/fis3-postpackager-loader-test](https://github.com/maxming2333/fis3-postpackager-loader-test)

**Comment by maxming2333** [comment]
`fis3 release` 后

可以在浏览器下看 

[http://127.0.0.1:5000/tpl/act/xzzt/tpl4/qmqz/qmqz.html](http://127.0.0.1:5000/tpl/act/xzzt/tpl4/qmqz/qmqz.html)

引用的 css

**Comment by maxming2333** [comment]
hello 有进展么？

**Comment by 2betop** [comment]
有啊，同名依赖还有包含 `qmqz.html` => `qmqz.scss`

所以 qmqz.scss 再前面，你把 html 的同名依赖关了就能让 qmqz 再后面。

比如你把 

```
// Global start

fis.match('/src/**', {
  useSameNameRequire: true
});
```

改成 


```
// Global start

fis.match('/src/**.js', {
  useSameNameRequire: true
});
```

**Comment by maxming2333** [comment]
好滴

**Comment by maxming2333** [comment]
重新讨论一下

`qmqz.html -> qmqz.scss`

这种依赖，可以在打包的时候设置为最后一个打包么，

因为一般项目都是自己页面单独的`css`是最后一个

即：

如果遇到 `qmqz.html -> qmqz.scss` 这种依赖，先看看有没有其他css依赖，然后先合并其他css，最后再合并 qmqz.scss

**Comment by maxming2333** [comment]
hello~
