### ISSUE TITLE
控制CSS的打包顺序

### ISSUE THREAD

**Issue by 303182519** [fex-team/fis3-postpackager-loader#72]
那么 js 的输出顺序就是：带 data-loader 的js，带 resource map 信息的js, 带 data-framework 的js，依赖中的 js, 页面中其他 js.

为什么CSS不搞个可以控制的

**Comment by 2betop** [comment]
看来是同一个问题 https://github.com/fex-team/fis3-postpackager-loader/issues/52#issuecomment-241434842
