### ISSUE TITLE
[fis3-postpackager-loader] 指定css打包地址无效

### ISSUE THREAD

**Issue by worry127722** [fex-team/fis3-postpackager-loader#8]
<img width="496" alt="9da3f265da4d94a720dd4bd1c1cedf0f" src="https://cloud.githubusercontent.com/assets/6937117/9054835/d6265c14-3ab7-11e5-929d-07bbc3bbd69a.png">

------
如图 已指定 css打包地址，但无文件生成

**Comment by 2betop** [comment]
link 没有 ref="stylesheet" 属性，所以不认为是 css 引用。

修改成以下写法就好了。

```html
<link type="text/css" rel="stylesheet" href="c.css">
```

**Comment by 2betop** [comment]
吾应该是跟没打包有关，和 css  打包异常有关。
