### ISSUE TITLE
打包后，个别文件还是没有合并到一起

### ISSUE THREAD

**Issue by shunzizhan** [fex-team/fis3-postpackager-loader#88]
all in one
![1](https://cloud.githubusercontent.com/assets/7811369/26517119/c641f6b6-42c4-11e7-990a-89a3eac6c06e.png)

不启用插件
![2](https://cloud.githubusercontent.com/assets/7811369/26517129/f4d78e00-42c4-11e7-8b6b-b0c192acc328.png)

**Comment by shunzizhan** [comment]
自己分析出原因了，在这个模块中，直接嵌入了一段script代码，导致下面紧接着的js不能合并，就没有与其他的组件合并到一起，给直接嵌入式的script代码后面添加就好了，但是这个地方就衍生出一个新问题，这个打包合并中间如果出现直接嵌入式script，后面如果只有一个外联的js文件，那个外联的js文件就不会打包合并在一起了
![3](https://cloud.githubusercontent.com/assets/7811369/26517341/393d0b84-42c9-11e7-97ba-b5dd206ffd8d.png)
![4](https://cloud.githubusercontent.com/assets/7811369/26517418/80caafa0-42ca-11e7-8602-c609e7062715.png)

**Comment by 2betop** [comment]
不要 内嵌和外链交叉用，只要交叉就不会打包一起的，不确定 他们之间是否有依赖关系，所以不敢合并。

**Comment by shunzizhan** [comment]
css没有交叉用，怎么有两个页面，也是没有合并到一起呢

**Comment by shunzizhan** [comment]
知道原因了
</head>被某人遗漏了
