### ISSUE TITLE
[fis3-postpackager-loader]  “includeAsyncs” 属性无效

### ISSUE THREAD

**Issue by worry127722** [fex-team/fis3-postpackager-loader#9]
allInOne 属性中添加了 includeAsyncs：true，同时js文件中添加require(['./indexp2'])， 但是并没有生成indexp2.js文件中的内容

**Comment by 2betop** [comment]
includeAsyncs 确实有问题，已经修复，不过要说明下，`require` 在没有 fis3-hook-module 的前提下是无效的。

**Comment by worry127722** [comment]
已修复
