### ISSUE TITLE
与packTo合并js的功能协作问题。

### ISSUE THREAD

**Issue by rainbowlee7** [fex-team/fis3-postpackager-loader#92]
html页面里面引用了 abcde五个js文件，另外有个packTo 打包了 bcd三个js文件到 A.js。A.js却自动引入到了html页面中。并不想引入A.js，而是希望abcde五个js文件合并为一个js文件插入到html中，有解决办法吗？

**Comment by xiangshouding** [comment]
那出就把 a b c d e 五个文件 packTo 到 pkg.js 不就好了？

另外毕竟 loader 实现的时候有其自己的理念在里面，如果不合适与你的项目，建议自己实现一个 loader。

**Comment by rainbowlee7** [comment]
谢谢回答，
真的只有自己再弄一个loader了.
前面的效果没有说清楚，是这样的：
page1.html 引用了 a b c d 
page2.html引用了  b c d e .
packTo  b c--->A.js
              a d --->B.js
              d e---->C.js
结果是：page1.html page2.html都引入了 A.js  B.js C.js----->>也就是只要packTo有，都会引入到html里面来。

**Comment by xiangshouding** [comment]
@rainbowlee7 对，是的，现在的打包插件的逻辑就是这样的。如果想用 all in one 或者其他方式的，请参考现在的打包插件自己定制一下。
