### ISSUE TITLE
能否提供支持抽离公共js代码功能

### ISSUE THREAD

**Issue by blackie4** [fex-team/fis3-postpackager-loader#97]
如题。
all in one后，单个文件过大，再者公共代码页面之间无法共用缓存
例如最后打包输出： common.js  ＋ page_aio.js
其中common.js可以配置多少个页面入口文件同时用到，则抽离到common.js中

**Comment by 2betop** [comment]
可以配合其他打包插件，比如 `packTo` 或者 deps-pack ，  loader 只会打包剩下的部分。
